services:
  - type: web
    plan: free
    name: suho-rename
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/naruto1427/Suho-rename
    branch: main
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: RKN_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: STRING_SESSION
        sync: false
      
